# Generated by Django 3.2.12 on 2022-05-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_todo_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
