# Generated by Django 2.2.27 on 2022-03-09 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220309_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
