# Generated by Django 3.2.12 on 2022-05-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_todo_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='profile',
            new_name='file',
        ),
    ]
