# Generated by Django 2.2.27 on 2022-03-09 14:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220309_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 3, 9, 14, 36, 24, 312209, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_on',
            field=models.DateField(default=datetime.datetime(2022, 3, 9, 14, 36, 24, 312237, tzinfo=utc)),
        ),
    ]
