# Generated by Django 2.2.27 on 2022-03-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220309_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_on',
            field=models.DateTimeField(),
        ),
    ]
