# Generated by Django 3.2.12 on 2022-04-06 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birth_date',
            new_name='date_of_birth',
        ),
    ]
