# Generated by Django 2.2.27 on 2022-03-09 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('created', models.DateField()),
                ('due_on', models.DateField()),
                ('owner', models.CharField(max_length=100)),
                ('mark', models.BooleanField(default=True)),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TodoList')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ('task',),
            },
        ),
    ]
