# Generated by Django 2.2.27 on 2022-03-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_on',
            field=models.DateTimeField(),
        ),
    ]
