# Generated by Django 2.2.27 on 2022-03-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220309_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_on',
            field=models.DateField(),
        ),
    ]
