# Generated by Django 2.2.27 on 2022-03-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220309_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_on',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
